name: Build TradeChest

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Copy pom.xml to project folder
        run: cp pom.xml TradeChest/tradechest-plugin/pom.xml

      - name: Build with Maven
        working-directory: TradeChest/tradechest-plugin
        run: mvn clean package

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: TradeChest
          path: TradeChest/tradechest-plugin/target/TradeChest-2.0.0.jar
